set-window-option -g mode-keys vi

set -g default-terminal "xterm-256color"
set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p2%s\\7"

set -g focus-events on
set -g allow-passthrough on
set -g set-clipboard on

# remap prefix from C-b to C-w
unbind C-b
set-option -g prefix C-w
bind-key C-w send-prefix

# split panes using | and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %
unbind C-Space

# disable Esc acting as a mod key
set -s escape-time 0

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# reload config file
bind r source-file ~/.tmux.conf

bind f resize-pane -Z

# Smart pane switching with awareness of Vim splits
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

is_fzf="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?fzf$'"

bind-key -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
bind -n C-j run "($is_vim && tmux send-keys C-j) || \
    ($is_fzf && tmux send-keys C-j) || \
    tmux select-pane -D"

bind -n C-k run "($is_vim && tmux send-keys C-k) || \
    ($is_fzf && tmux send-keys C-k) || \
    tmux select-pane -U"

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# Vi mode for copy and paste
bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -i -selection clipboard'
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# move x clipboard into tmux paste buffer
bind C-p run "tmux set-buffer \"$(xclip -o -selection clipboard)\"; tmux paste-buffer"
# move tmux copy buffer into x clipboard
bind C-y run "tmux show-buffer | clip -in -selection clipboard > /dev/null"
